[project]
name = "Balethon"
version = "0.0.1"
authors = [
  { name="Sajjad", email="sajjadalipour2006@gmail.com" },
    {name="Abolfazl Amiri", email=""}
]
description = "A library for creating bots in Bale"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Framework :: aiohttp",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/SajjadAlipour2006/Balethon"
"Tracker" = "https://github.com/SajjadAlipour2006/Balethon/issues"
"Community" = "ble.ir/join/MTlhN2Q2Mz"